### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by patrickvandenbulcke** [krauskopf/node-red-contrib-car-bmw#28] opened 2023-05-31 08:11 UTC
Hello,
not really an issue, but don't know where to post it otherwise.
the node-red nodes work perfectly. But I wonder: Would it be possible to set the max AC charging rate directly through node-red?

In the BMW App I can set the max charging rate (AMPS). This would make it very interesting because I could set the Max charging rate to be inline with the amount of Watts my solarpanels are currently producing. As such I would be able to charge the car without taking anything from the grid.

It should be possible, because you can manually set this in the myBMW app.

this would be an amazing feature.

**Comment by delcomp** [comment] 2023-06-29 20:05
This would be a really interesting feature.
I'm using the Tesla API do the exact same thing for my Tesla, works brilliantly. My wife now drives a BMW iX3 and I'd like to do same for her car.
I'll follow this feature request.

**Comment by krauskopf** [comment] 2023-07-30 21:04
Seems to be a duplicate of #35

**Comment by krauskopf** [comment] 2023-07-31 20:40
Hi @patrickvandenbulcke,  @delcomp 
please upgrade to v0.5.1 and have a look if the flow from #35 also works for you.

**Closed** 2023-08-06 11:21 UTC
Labels: enhancement

**Comment by patrickvandenbulcke** [comment] 2023-08-06 17:42
hello, I tested it
works great! 

thanks for this super addition !!!
